import { Payment } from "@mui/icons-material";
// import Aquariumdetailss from "./pages/Aquariumdetailss";

export const Routes = {
  // pages
  // dynamicpopup: { path: "/dynamicpopup" },
  Presentation: { path: "/Presentation" },
  DashboardOverview: { path: "/dashboard/overview" },
  Transactions: { path: "/transactions" },
  Category: { path: "/category" },
  Groomingdetail: { path: "/Groomingdetail" },
  Vetservices: { path: "/Vetservices" },
  Petvendor: { path: "/Petvendor" },
  Petmarketdetails: { path: "/Petmarketdetails" },
  Consultant: { path: "/Consultant" },
  Aquarium: { path: "/Aquarium" },
  Event: { path: "/Event" },

  PetInsurance: { path: "/PetInsurance" },
  Insurancedetails: { path: "/Insurancedetails" },
  Petmedicines: { path: "/Petmedicines" },
  Aquariumdetailss: { path: "/Aquariumdetailss" },
  Trainingvenderdetail: { path: "/Trainingvenderdetail" },
  Eventdetails: { path: "/Eventdetails" },
  Aquariumdetails: { path: "/Aquariumdetails" },
  Topics: { path: "/topics" },
  Vetservicedetails: { path: "/Vetservicedetails" },
  Photographyvenderdetails: { path: "/Photographyvenderdetails" },
  SubscriptionData: { path: "/subscriptiondata" },
  Content: { path: "/content" },
  Medicine: { path: "/medicine" },
  Exam: { path: "/exam" },
  Vetservicedetail: { path: "/Vetservicedetail" },
  Complete: { path: "/Complete" },
  Processing: { path: "/Processing" },
  Petmarket: { path: "/Petmarket" },
  Petmedicinesdetails: { path: "/Petmedicinesdetails" },
  Payment: { path: "/Payment" },
  Kyc: { path: "/Kyc" },
  SubscriptionPlan: { path: "/SubscriptionPlan" },

  Kycdetails: { path: "/Kycdetails" },


  Consultantdetails: { path: "/Consultantdetails" },
  Grooming: { path: "/Grooming" },
  Petfriendly: { path: "/Petfriendly" },
  PetHostel: { path: "/PetHostel" },
  Adoptioncenter: { path: "/Adoptioncenter" },
  Photographydetail: { path: "/Photographydetail" },
  Trainingdetail: { path: "/Trainingdetail" },
  Trainingcenter: { path: "/Trainingcenter" },
  Photography: { path: "/Photography" },
  Pethosteldetails: { path: "/Pethosteldetails" },
  Notification: { path: "/notification" },
  Banner: { path: "/banner" },
  Quations: { path: "/questions" },
  Vendor: { path: "/Vendor" },
  User: { path: "/User" },
  CommanForm: { path: "/bulkUpload" },

  Book: { path: "/Book" },
  UserDetails: { path: "/userDetails" },
  QuestionDetails: { path: "/questionDetails" },
  MockQuestionDetails: { path: "/mockQuestionDetails" },
  Upgrade: { path: "/upgrade" },
  BootstrapTables: { path: "/tables/bootstrap-tables" },
  Billing: { path: "/examples/billing" },
  Invoice: { path: "/examples/invoice" },
  Signin: { path: "/examples/sign-in" },
  Signin: { path: "/" },

  Signup: { path: "/examples/sign-up" },
  ForgotPassword: { path: "/examples/forgot-password" },
  ResetPassword: { path: "/examples/reset-password" },
  Lock: { path: "/examples/lock" },
  NotFound: { path: "/examples/404" },
  ServerError: { path: "/examples/500" },
  Positions: { path: "/positions" },

  // docs
  DocsOverview: { path: "/documentation/overview" },
  DocsDownload: { path: "/documentation/download" },
  DocsQuickStart: { path: "/documentation/quick-start" },
  DocsLicense: { path: "/documentation/license" },
  DocsFolderStructure: { path: "/documentation/folder-structure" },
  DocsBuild: { path: "/documentation/build-tools" },
  DocsChangelog: { path: "/documentation/changelog" },

  // components
  Accordions: { path: "/components/accordions" },
  Alerts: { path: "/components/alerts" },
  Badges: { path: "/components/badges" },
  Widgets: { path: "/widgets" },
  Breadcrumbs: { path: "/components/breadcrumbs" },
  Buttons: { path: "/components/buttons" },
  Forms: { path: "/components/forms" },
  Modals: { path: "/components/modals" },
  Navs: { path: "/components/navs" },
  Navbars: { path: "/components/navbars" },
  Pagination: { path: "/components/pagination" },
  Popovers: { path: "/components/popovers" },
  Progress: { path: "/components/progress" },
  Tables: { path: "/components/tables" },
  Tabs: { path: "/components/tabs" },
  Tooltips: { path: "/components/tooltips" },
  Toasts: { path: "/components/toasts" },
  WidgetsComponent: { path: "/components/widgets" },
  Groomingdetails: { path: "/Groomingdetails" },
  Setting: { path: "/setting" },
  MockExamCategory: { path: "/mockExamCategory" },
  MockExam: { path: "/mockExam" },
  Petmarketdetailss: { path: "/Petmarketdetailss" },
  Petservices: { path: "/Petservices" },
  Categorys: { path: "/Categorys" },
  // dynamicpopup: { path: "/dynamicpopup" },
};
